---
- name: Start Zebra
  command: /usr/bin/zebrasrv-2.0 -D -T -p /var/run/zebrasrv.pid -f /etc/koha/koha-conf.xml -l /var/log/koha/zebrasrv.log
  args:
    creates: /var/run/zebrasrv.pid
  environment:
    KOHA_CONF: /etc/koha/koha-conf.xml
    PERL5LIB: /usr/share/koha/lib
- name: Build Zebra indices
  command: ./rebuild_zebra.pl -b -a -r -v
  args:
    chdir: /usr/share/koha/bin/migration_tools/
    creates: /tmp/zebra_koha/rebuild/rebuild..LCK
  environment:
    KOHA_CONF: /etc/koha/koha-conf.xml
    PERL5LIB: /usr/share/koha/lib
  become: true
  become_user: koha
- name: Restart Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - httpd
    - koha-index-daemon
    - postfix
