---
- name: Start Zebra
  command: . /etc/rc.d/rc.local
- name: Restart Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - httpd
    - koha-index-daemon
    - stunnel
    - postfix
